apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 7777
    targetPort: 7777
    nodePort: 31110