apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-controller
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard-rwo
  

